services:
  - type: web
    name: student-alcohol-monitoring
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
